steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/money-map:latest',
      '.'
    ]

images:
  - 'gcr.io/$PROJECT_ID/money-map:latest'
