from langchain.tools import tool
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import os
from dotenv import load_dotenv

load_dotenv(os.path.join(r'C:\My Projects\Money-Map\credentials.env'))

@tool
def send_financial_report_email(report_content: str, user_email: str) -> str:
    """
    Send a financial summary report to the user's email.
    
    Args:
        report_content: The financial report text to send
        user_email: The recipient's email address
    
    Returns:
        str: Success or failure message
    """
    from_email = os.getenv('APP_ACCOUNT_EMAIL_ADDRESS')
    password = os.getenv('APP_ACCOUNT_PASSWORD')
    
    msg = MIMEMultipart()
    msg['From'] = from_email
    msg['To'] = user_email
    msg['Subject'] = 'Money Map - Your Financial Summary Report'
    
    # HTML body with proper formatting
    html_body = f"""
    <html>
        <body style="font-family: Arial, sans-serif; padding: 20px; background-color: #f5f5f5;">
            <div style="max-width: 600px; margin: 0 auto; background-color: white; padding: 30px; border-radius: 10px;">
                <h2 style="color: #10b981; border-bottom: 2px solid #10b981; padding-bottom: 10px;">
                    Financial Summary Report
                </h2>
                <div style="color: #333; line-height: 1.6; white-space: pre-wrap;">
                    {report_content}
                </div>
                <hr style="margin: 20px 0; border: none; border-top: 1px solid #ddd;">
                <p style="color: #666; font-size: 12px; text-align: center;">
                    Generated by Money Map - Your Personal Finance Tracker
                </p>
            </div>
        </body>
    </html>
    """
    
    msg.attach(MIMEText(html_body, 'html'))
    
    try:
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(from_email, password)
        server.send_message(msg)
        server.quit()
        return f"✓ Financial report successfully sent to {user_email}"
    except Exception as e:
        return f"✗ Failed to send email: {str(e)}"